name: Download
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  download:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get Host User Group
        id: host
        shell: bash
        run: |
          echo "hostgroup=`id -g`" >> $GITHUB_OUTPUT
          echo "hostuser=`id -u`" >> $GITHUB_OUTPUT

      - name: Test Host User Group
        shell: bash
        run: |
          echo "hostgroup=${{ steps.host.outputs.hostuser }}"
          echo "hostuser=${{ steps.host.outputs.hostgroup }}"

      - name: Docker Build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: "Dockerfile-download"
          load: true
          tags: gigaohmbio-download:latest
          push: false

      - name: Docker Run
        uses: tj-actions/docker-run@v2
        with:
          image: gigaohmbio-download:latest
          name: gigaohmbio-download-1
          options: --user 1000:1000 -v ${{ github.workspace }}/data:/home/pn/app/data
      
      - name: Verify
        shell: bash
        run: |
          ls -l ${{ github.workspace }}
          ls -l ${{ github.workspace }}/data
          cat ${{ github.workspace }}/data/dl-output.txt
          test `tail -1 ${{ github.workspace }}/data/log.txt` = "DOWNLOAD_OK"