name: Download
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  download:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Action Variables
        id: avars
        shell: bash
        run: |
          echo "hostuser=`id -u`" >> $GITHUB_OUTPUT
          echo "hostgroup=`id -g`" >> $GITHUB_OUTPUT
          echo "bindmountvol=data/`date +%Y%m%d-%H%M%S`" >> $GITHUB_OUTPUT

      - name: Test Action Variables
        shell: bash
        run: |
          echo "hostuser=${{ steps.avars.outputs.hostuser }}"
          echo "hostgroup=${{ steps.avars.outputs.hostgroup }}"
          echo "bindmountvol=${{ steps.avars.outputs.bindmountvol }}"
          mkdir -p ${{ steps.avars.outputs.bindmountvol }}

      - name: Docker Build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: "Dockerfile-download"
          load: true
          tags: gigaohmbio-download:latest
          push: false
          build-args: |
            UID=${{ steps.avars.outputs.hostuser }}
            GID=${{ steps.avars.outputs.hostgroup }}

      - name: Docker Run
        uses: tj-actions/docker-run@v2
        with:
          image: gigaohmbio-download:latest
          name: gigaohmbio-download-1
          options: -v ${{ github.workspace }}/${{ steps.avars.outputs.bindmountvol }}:/home/pn/app/data
      
      - name: Verify
        id: verify
        shell: bash
        run: |
          ls -l ${{ github.workspace }}/${{ steps.avars.outputs.bindmountvol }}
          test `tail -1 ${{ github.workspace }}/${{ steps.avars.outputs.bindmountvol }}/log.txt` = "DOWNLOAD_OK"
          echo "audiofile="$(echo "$(tail -2 ${{ github.workspace }}/${{ steps.avars.outputs.bindmountvol }}/log.txt)" | head -n 1)"" >> $GITHUB_OUTPUT
      
      - name: Output Test
        shell: bash
        run: |
          echo "AUDIO_FILE=${{ steps.verify.outputs.audiofile }}"